# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb21be677afcfd30f5052181f2c40cdf"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "local-pickup"
handle = "local-pickup-22"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_write_customers,customer_read_customers,read_customers,write_customers,read_products,write_cart_transforms"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
